### ISSUE TITLE
UML State Diagram

### ISSUE THREAD

**Issue by syeaw0** [syeaw0/Class-Project-iRobots#6]

**Comment by ghost** [comment]
![irobotthebombstatediagrampt1](https://cloud.githubusercontent.com/assets/10226256/7035548/96030bae-dd3e-11e4-9a13-31f5cbc9a4f6.jpg)
![irobotthebombstatedrawingpt2](https://cloud.githubusercontent.com/assets/10226256/7035549/96186b52-dd3e-11e4-96b0-c7a291c59420.jpg)
